### PR TITLE
add a dev release

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @rsignell-usgs

### CODE REVIEW

**Comment by philippjfr** [comment]
We're planning to release tomorrow, is releasing the dev release urgent?

**Comment by rsignell-usgs** [comment]
I was considering using this for a demo in 1.5 hours. :)

**Comment by philippjfr** [comment]
No objection then.

**Comment by rsignell-usgs** [comment]
@philippjfr can you approve as a reviewer?

**Review by philippjfr — APPROVED** [review]

**Pull request merged**
