### PR TITLE
Pin bokeh<2.0.1 for HoloViews 1.13.0

### PR DESCRIPTION
**Pull request by philippjfr**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by philippjfr** [comment]
Stupidly created a branch here. I'll close since this is already published now and I'd have to revert the changes in this PR in the next one anyway.

**Comment by jakirkham** [comment]
Probably ok to just merge then 🙂

**Comment by philippjfr** [comment]
Okay, should have done, wasn't sure if it would try to push another package if I did that.

**Comment by jakirkham** [comment]
Ah no worries. It won't. We check if the packages are already uploaded and skip uploading if so.

**Comment by philippjfr** [comment]
Good to know thanks. Btw while I've got you, what's the suggested workflow for patching older releases, e.g. if I wanted to update a pin? Would that be a good reason to use a branch?

**Comment by jakirkham** [comment]
Haha. Was just writing that answer 😉

We can hot-fix the metadata to ensure this constraint is added to all `holoviews` packages. The hot-fixes are made in [`conda-forge-repodata-patches`]( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock ). Here's how we made a similar change for `distributed` w.r.t. `msgpack-python` ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/32 ).

**Comment by philippjfr** [comment]
Neat, the particular pin I'd need to get in is that all HoloViews version <1.13.0 should pin bokeh<2.0 (should have done this a week ago). Should I give that a shot?

**Comment by jakirkham** [comment]
Go for it! Happy to review 😄

**Comment by philippjfr** [comment]
@jakirkham Here is my attempt: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/38

**Pull request closed without merging**
