### PR TITLE
Include license

### PR DESCRIPTION
**Pull request by jakirkham**
Make sure the license file is included in the package.

### CODE REVIEW

**Comment by jlstevens** [comment]
Thanks! 

We'll be updating the holoviews conda-forge recipe shortly for the 1.9 release so I hope we can get this PR merged ASAP.

**Comment by jakirkham** [comment]
Right. Happy to have this pulled into the update PR instead. The build number bump in the last commit can just be dropped.

**Comment by jlstevens** [comment]
Either way is fine by me. I would bump the build number back down to zero for the 1.9 recipe.

**Comment by jlstevens** [comment]
Tests have passed. Merging.

**Comment by jakirkham** [comment]
Thanks!

**Pull request merged**
