### PR TITLE
Updated recipe to version 1.8.0

### PR DESCRIPTION
**Pull request by jlstevens**
Updating recipe to bump HoloViews version from a fork, as requested in #7.

### CODE REVIEW

**Comment by jlstevens** [comment]
@ocefpaf Any suggestions regarding what I need to fix to get the tests passing and this PR merged?

**Comment by jlstevens** [comment]
I added numpy to the build requirements as there seemed to be a numpy error...

**Comment by philippjfr** [comment]
Looks good and passing now.

**Comment by ocefpaf** [comment]
> @ocefpaf Any suggestions regarding what I need to fix to get the tests passing and this PR merged?

Just for here but it seems that everything is resolved now :smile:

**Comment by jlstevens** [comment]
@ocefpaf I'm just wondering if I'm missing a step or just being impatient...

image

Thanks!

**Comment by ocefpaf** [comment]
We don't seem to have `holoviews` for `OS X` since the start of this `feedstock`. See https://anaconda.org/conda-forge/holoviews/files but the build is not skipped on OS X :unamused: 

The package is built but the upload seems broken: https://travis-ci.org/conda-forge/holoviews-feedstock/jobs/250587222

Looking into it. Hold on...

**Comment by ocefpaf** [comment]
See #9

**Pull request merged**
